/**
 * @file web_ui.h
 * The SPEC §12.1 web UI, served from flash as one self-contained page.
 *
 * Compiled in as a C string rather than embedded as a binary: none of the ESP-IDF
 * binary-embedding routes works under this toolchain, because PlatformIO parses CMake
 * for sources and flags but builds with SCons, so the assembly file that EMBED_FILES
 * and target_add_binary_data generate through a CMake custom command is never produced
 * (the same finding as the acoustic fixtures, recorded in src/CMakeLists.txt).
 *
 * No external assets, no CDN, no build step: the board is an isolated access point with
 * no route to the internet, so anything the page does not carry itself cannot load. That
 * rules out web fonts and icon sets; everything here is system fonts and CSS.
 *
 * The page is a STATE MIRROR, not a data processor (SPEC §12.2). It renders what the
 * firmware reports and never computes machine state of its own. Two consequences worth
 * stating because they look like duplication:
 *
 *   - `active_wait` and its wait_id come ONLY from a state snapshot, never from a
 *     WAIT_ISSUED event, because the wait_id is the SPEC §12.3 safety contract and the
 *     snapshot is what the firmware calls authoritative.
 *   - the phase caption (measuring / positioning / ...) is driven straight off
 *     STATE_TRANSITION events. That is still mirroring - the caption is the `to` field
 *     the firmware sent - and it is what removed four of the five snapshot round trips
 *     the UI used to make per spoke.
 *
 * The design problem this page solves is cause and effect, not decoration. A measurement
 * takes ~3.85 s of DSP while the ack for the button that started it comes back in ~50 ms
 * (measured on the Nano over WiFi). An operator therefore needs to be told four separate
 * things - sent, accepted, working, finished - or the machine looks broken for four
 * seconds. Every one of those has its own visible state here, and the elapsed counter
 * during work is real elapsed time, never a fabricated progress bar.
 *
 * Single quotes throughout so the C string literal needs no escaping.
 */
#ifndef TRUING_WEB_UI_H
#define TRUING_WEB_UI_H

static const char TRUING_WEB_UI_HTML[] =
"<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1,viewport-fit=cover'>\n"
"<title>Truing Machine</title><style>\n"
":root{--bg:#0f1115;--card:#171a21;--card2:#1e222b;--fg:#e9ecf1;--dim:#8b93a1;\n"
" --line:#282d38;--ok:#4fc08d;--warn:#e8a13f;--bad:#e85c5c;--run:#54a8e0;--pad:14px}\n"
"*{box-sizing:border-box}html{-webkit-text-size-adjust:100%}\n"
"body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.5 ui-monospace,\n"
" SFMono-Regular,Menlo,Consolas,monospace;padding-bottom:env(safe-area-inset-bottom)}\n"
"header{position:sticky;top:0;z-index:5;display:flex;gap:10px;align-items:center;\n"
" padding:11px var(--pad);background:#0f1115ee;border-bottom:1px solid var(--line)}\n"
"h1{font-size:14px;margin:0;font-weight:600;letter-spacing:.04em}\n"
"#dot{width:9px;height:9px;border-radius:50%;background:var(--bad);flex:none;\n"
" box-shadow:0 0 0 3px #e85c5c22}\n"
"#dot.up{background:var(--ok);box-shadow:0 0 0 3px #4fc08d22}\n"
"#conn{margin-left:auto;font-size:11px;color:var(--dim);letter-spacing:.06em;\n"
" text-transform:uppercase}\n"
"main{display:grid;grid-template-columns:minmax(340px,1fr) minmax(340px,1fr);\n"
" gap:var(--pad);padding:var(--pad);align-items:start}\n"
"@media(max-width:860px){main{grid-template-columns:1fr;padding:10px;gap:10px}}\n"
".col{display:flex;flex-direction:column;gap:var(--pad);min-width:0}\n"
"@media(max-width:860px){.col{gap:10px}}\n"
".card{background:var(--card);border:1px solid var(--line);border-radius:10px;\n"
" padding:12px 14px;min-width:0}\n"
".card>h2{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:var(--dim);\n"
" margin:0 0 10px;font-weight:600;display:flex;align-items:center;gap:8px}\n"
".card>h2 .sp{margin-left:auto}\n"

/* progress strip */
".prog{font-size:11px;color:var(--dim);letter-spacing:.06em;display:flex;gap:8px;\n"
" text-transform:uppercase;margin-bottom:6px}\n"
".prog b{color:var(--fg);font-weight:600}\n"
".bar{height:4px;background:#0d0f13;border-radius:3px;overflow:hidden;margin-bottom:12px}\n"
".bar i{display:block;height:100%;background:var(--run);width:0;transition:width .25s}\n"

/* the operator block */
"#opcard{border-color:#2f3543}\n"
"#opcard.wait{border-color:var(--warn);box-shadow:0 0 0 1px #e8a13f33,0 6px 22px #0006}\n"
"#opcard.busy{border-color:var(--run);box-shadow:0 0 0 1px #54a8e033}\n"
"#opcard.good{border-color:var(--ok);box-shadow:0 0 0 1px #4fc08d33}\n"
"#opcard.err{border-color:var(--bad);box-shadow:0 0 0 1px #e85c5c33}\n"
".tag{font-size:10px;letter-spacing:.14em;text-transform:uppercase;font-weight:700;\n"
" margin-bottom:3px}\n"
".tag.w{color:var(--warn)}.tag.b{color:var(--run)}.tag.g{color:var(--ok)}\n"
".tag.e{color:var(--bad)}.tag.d{color:var(--dim)}\n"
".big{font:700 clamp(34px,11vw,54px)/1.06 ui-monospace,SFMono-Regular,Menlo,Consolas,\n"
" monospace;letter-spacing:-.02em;display:flex;align-items:baseline;gap:10px;margin:2px 0 4px}\n"
".big .u{font-size:14px;font-weight:600;color:var(--dim);letter-spacing:.06em}\n"
".dir{display:inline-block;font-size:11px;font-weight:700;letter-spacing:.1em;\n"
" padding:3px 9px;border-radius:999px;margin-bottom:6px}\n"
".dir.t{background:#2a4a38;color:#8fe0b4}.dir.l{background:#4a3a2a;color:#e8c48f}\n"
".say{opacity:.85;margin:0 0 12px;font-size:13px}\n"
".shim{height:3px;border-radius:2px;margin:10px 0 12px;background:#0d0f13;overflow:hidden}\n"
".shim i{display:block;height:100%;width:34%;border-radius:2px;background:var(--run);\n"
" animation:sl 1.1s ease-in-out infinite}\n"
"@keyframes sl{0%{transform:translateX(-100%)}100%{transform:translateX(390%)}}\n"
".el{font-size:12px;color:var(--dim);font-variant-numeric:tabular-nums}\n"

/* controls */
"button{font:inherit;background:var(--card2);color:var(--fg);border:1px solid var(--line);\n"
" border-radius:8px;padding:9px 13px;cursor:pointer;min-height:40px}\n"
"button:hover:not(:disabled){background:#262b36;border-color:#3a414f}\n"
"button:active:not(:disabled){transform:translateY(1px)}\n"
"button:disabled{opacity:.35;cursor:not-allowed}\n"
"button.go{background:#1f5540;border-color:#2b6d52;color:#d8f5e6;font-weight:600}\n"
"button.go:hover:not(:disabled){background:#256549}\n"
"button.stop{background:#54282a;border-color:#6d3538;color:#f6dada}\n"
"button.wide{width:100%;min-height:54px;font-size:16px;font-weight:700;letter-spacing:.03em}\n"
"button.tiny{min-height:0;padding:2px 8px;font-size:10px;letter-spacing:.08em;\n"
" text-transform:uppercase}\n"
".row{display:flex;gap:8px;flex-wrap:wrap}.row>button{flex:1 1 auto}\n"
".sep{border:0;border-top:1px solid var(--line);margin:12px 0}\n"
"input{font:inherit;background:#0d0f13;color:var(--fg);border:1px solid var(--line);\n"
" border-radius:8px;padding:10px;width:100%;min-height:44px}\n"
".fields{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px}\n"
".fl{font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:var(--dim);\n"
" display:block;margin-bottom:4px}\n"
"#hint{font-size:11px;color:var(--dim);margin-top:8px;min-height:1em}\n"
"#hint.bad{color:var(--bad)}#hint.good{color:var(--ok)}\n"

/* state + feeds */
".kv{display:grid;grid-template-columns:auto 1fr;gap:7px 14px;margin:0;font-size:13px}\n"
".kv dt{color:var(--dim)}.kv dd{margin:0;word-break:break-word;text-align:right}\n"
".pill{display:inline-block;padding:2px 9px;border-radius:999px;font-size:11px;\n"
" font-weight:700;letter-spacing:.06em;background:#2a303c;color:var(--dim)}\n"
".pill.ok{background:#1f4636;color:#8fe0b4}.pill.run{background:#1d3f57;color:#a5d6f5}\n"
".pill.warn{background:#4a3a1f;color:#e8c48f}.pill.done{background:#33384a;color:#b9c2d6}\n"
".feed{height:min(52vh,460px);overflow-y:auto;background:#0d0f13;border-radius:8px;\n"
" padding:6px;border:1px solid #1b1f28}\n"
"@media(max-width:860px){.feed{height:36vh}}\n"
".feed>div{padding:4px 7px;border-radius:5px;display:flex;gap:9px;white-space:pre-wrap;\n"
" word-break:break-word}\n"
".feed>div:nth-child(odd){background:#ffffff05}\n"
".feed .ts{color:#5d6675;flex:none;font-variant-numeric:tabular-nums;font-size:11px}\n"
"#dbg{font-size:11px}\n"
".t-ack{color:var(--dim)}.t-bad{color:var(--bad)}.t-good{color:var(--ok)}\n"
".t-warn{color:var(--warn)}.t-nav{color:var(--run)}.t-pend{color:var(--dim);opacity:.7}\n"
"pre{background:#0d0f13;border:1px solid #1b1f28;border-radius:8px;padding:10px;\n"
" font-size:11px;line-height:1.45;max-height:260px;overflow:auto;margin:0}\n"
"pre.empty{color:var(--dim)}\n"
".hide{display:none}\n"
"</style></head><body>\n"

"<header><span id='dot'></span><h1>Truing Machine</h1>\n"
"<span id='conn'>connecting</span></header>\n"
"<main>\n"
" <div class='col'>\n"
"  <div class='card' id='opcard'>\n"
"   <div class='prog'><span id='pass'>&nbsp;</span><b id='pos' class='sp'></b></div>\n"
"   <div class='bar'><i id='barfill'></i></div>\n"
"   <div id='prompt'></div>\n"
"   <div id='answer'></div>\n"
"   <hr class='sep'>\n"
"   <div class='row'>\n"
"    <button class='go' id='b-start'>Start truing</button>\n"
"    <button class='stop' id='b-abort'>Abort</button>\n"
"    <button id='b-refresh'>Resync</button>\n"
"    <button id='b-prov'>Provenance</button>\n"
"   </div>\n"
"   <div id='hint'></div>\n"
"  </div>\n"
"  <div class='card'><h2>Machine state</h2>\n"
"   <dl class='kv'><dt>state</dt><dd id='st'>-</dd>\n"
"   <dt>session</dt><dd id='se'>-</dd>\n"
"   <dt>cycle</dt><dd id='cy'>-</dd>\n"
"   <dt>last result</dt><dd id='lr'>-</dd></dl>\n"
"  </div>\n"
"  <div class='card'><h2>Current cycle provenance</h2>\n"
"   <pre id='prov' class='empty'>Ask for it with the Provenance button.</pre>\n"
"  </div>\n"
" </div>\n"
" <div class='col'>\n"
"  <div class='card'><h2>Activity<button class='tiny sp' id='b-dbg'>Show protocol</button></h2>\n"
"   <div class='feed' id='act'></div>\n"
"   <div class='feed hide' id='dbg'></div>\n"
"  </div>\n"
" </div>\n"
"</main>\n"

"<script>\n"
"var ws=null,snap=null,seq=0,pending=null,curState=null,nSpokes=0,lastIdx=null;\n"
"var busySince=0,tick=null,flash=null;\n"
"function el(id){return document.getElementById(id);}\n"
"function mk(t,c,x){var e=document.createElement(t);if(c)e.className=c;\n"
" if(x!==undefined)e.textContent=x;return e;}\n"
"function hms(ms){var s=ms/1000,m=Math.floor(s/60);\n"
" return m+':'+(s-m*60).toFixed(1).padStart(4,'0');}\n"

/* Two feeds. The operator one carries only things a person did or the machine finished;
   the protocol one carries every frame, which is where acks and raw transitions live. */
"function feed(which,text,cls,ts){var d=mk('div');\n"
" d.appendChild(mk('span','ts',ts===undefined?'':hms(ts)));\n"
" d.appendChild(mk('span',cls||'',text));\n"
" var L=el(which);var stick=L.scrollTop+L.clientHeight>=L.scrollHeight-24;\n"
" L.appendChild(d);while(L.childNodes.length>300){L.removeChild(L.firstChild);}\n"
" if(stick)L.scrollTop=L.scrollHeight;return d;}\n"
"function act(text,cls,ts){return feed('act',text,cls,ts);}\n"
"function dbg(text,cls,ts){return feed('dbg',text,cls,ts);}\n"

"function send(o){if(!ws||ws.readyState!==1){hint('not connected',1);return 0;}\n"
" o.seq=++seq;ws.send(JSON.stringify(o));dbg('-> '+JSON.stringify(o),'t-ack');return o.seq;}\n"
"function hint(t,bad){var h=el('hint');h.textContent=t||'';\n"
" h.className=bad===1?'bad':(bad===2?'good':'');}\n"

/* ---- command lifecycle ---------------------------------------------------------------
   Four distinct things the operator must be able to tell apart: sent, accepted, working,
   finished. The button is disabled the instant it is clicked, so a second press cannot
   produce a second command; the ack is matched on seq, and the wait_id it answers is
   remembered so a rejection can say which wait it was about. */
"function submit(intent,waitId,extra){\n"
" if(pending)return;\n"
" var o={cmd:intent,wait_id:waitId};\n"
" if(extra)for(var k in extra)o[k]=extra[k];\n"
" var s=send(o);if(!s)return;\n"
" pending={seq:s,waitId:waitId,intent:intent,t0:Date.now(),\n"
"  node:act('you: '+verb(intent)+' (sending)','t-pend')};\n"
" pending.timer=setTimeout(function(){\n"
"  if(!pending)return;\n"
"  pending.node.lastChild.textContent='you: '+verb(pending.intent)+' - NO REPLY';\n"
"  pending.node.lastChild.className='t-bad';\n"
"  hint('No reply from the machine after 6 s. Still connected? Press Resync.',1);\n"
"  pending=null;render();},6000);\n"
" render();}\n"
"function verb(i){\n"
" if(i==='CONFIRM_POSITIONED')return 'positioned';\n"
" if(i==='CONFIRM_ADJUSTMENT_DONE')return 'adjustment applied';\n"
" if(i==='SUBMIT_RUNOUT')return 'runout entered';\n"
" return i;}\n"

"function connect(){\n"
" ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws');\n"
" ws.onopen=function(){el('conn').textContent='connected';el('dot').className='up';\n"
"  act('connected','t-good');\n"
"  /* Once on connect, and again only on reconnect or desync: the pushes carry the rest. */\n"
"  send({cmd:'GET_CURRENT_STATE'});send({cmd:'GET_CURRENT_CYCLE_PROVENANCE'});};\n"
" ws.onclose=function(){el('conn').textContent='reconnecting';el('dot').className='';\n"
"  act('connection lost - retrying','t-warn');\n"
"  if(pending){clearTimeout(pending.timer);pending=null;}\n"
"  setTimeout(connect,1500);};\n"
" ws.onmessage=function(m){var f;try{f=JSON.parse(m.data);}catch(e){return;}handle(f);};}\n"

"function handle(f){\n"
" if(f.t==='state'){snap=f;curState=f.current_state;render();return;}\n"
" if(f.t==='provenance'){var p=el('prov');p.className='';\n"
"  p.textContent=JSON.stringify(f,null,1);\n"
"  if(f.wheel_state_summary&&f.wheel_state_summary.n_spokes){\n"
"   nSpokes=f.wheel_state_summary.n_spokes;render();}\n"
"  dbg('provenance '+JSON.stringify(f).length+' bytes','t-ack');return;}\n"
" if(f.t==='ack'){onAck(f);return;}\n"
" if(f.t!=='event')return;\n"
" onEvent(f);}\n"

"function onAck(f){\n"
" var what=f.intent||f.cmd_kind;\n"
" dbg('ack seq '+f.seq+' '+what+' '+(f.accepted?'accepted':\n"
"  ('REJECTED '+(f.verdict||f.wire))),f.accepted?'t-ack':'t-bad');\n"
" if(pending&&f.seq===pending.seq){\n"
"  clearTimeout(pending.timer);\n"
"  if(f.accepted){\n"
"   pending.node.lastChild.textContent='you: '+verb(pending.intent)+' - accepted';\n"
"   pending.node.lastChild.className='t-good';\n"
"   flash={tag:'g',title:'CONFIRMED',say:'The machine has your answer.'};\n"
"   setTimeout(function(){flash=null;render();},900);\n"
"   pending=null;hint('');render();return;}\n"
"  var why=(f.verdict||f.wire)+(f.reason&&f.reason!=='NONE'?' / '+f.reason:'');\n"
"  pending.node.lastChild.textContent='you: '+verb(pending.intent)+' - REFUSED '+why;\n"
"  pending.node.lastChild.className='t-bad';\n"
"  pending=null;\n"
"  hint(why+explain(f.verdict),1);\n"
"  send({cmd:'GET_CURRENT_STATE'});return;}\n"
" if(!f.accepted){\n"
"  var w2=(f.verdict||f.wire)+(f.reason&&f.reason!=='NONE'?' / '+f.reason:'');\n"
"  act(what+' refused: '+w2,'t-bad');\n"
"  hint(w2+explain(f.verdict),1);\n"
"  send({cmd:'GET_CURRENT_STATE'});}}\n"

"function explain(v){\n"
" if(v==='REJECT_STATE')return ' - not allowed in state '+(curState||'?')+'.';\n"
" if(v==='REJECT_NO_ACTIVE_WAIT')return ' - there is no wait to answer.';\n"
" if(v==='REJECT_STALE_INTENT')\n"
"  return ' - that wait was already answered; the machine has moved on.';\n"
" return '';}\n"

/* One activity line per thing that happened to the operator, not one per transition.
   The raw transitions all still go to the protocol feed. */
"function onEvent(f){var k=f.kind;\n"
" if(k==='STATE_TRANSITION'){\n"
"  dbg(f.from+' -> '+f.to,'',f.ts_ms);\n"
"  /* Elapsed is per phase and is real: reset it when the phase itself changes, not on\n"
"     every re-render, and never advance it for a phase that is not running. */\n"
"  if(f.to!==curState)busySince=Date.now();\n"
"  curState=f.to;\n"
"  /* Left the wait: drop the stale prompt now rather than after the snapshot. */\n"
"  if(f.from==='WAIT_FOR_OPERATOR'&&snap)snap.active_wait=null;\n"
"  if(f.to==='MEASURE_SPOKE_TENSION')\n"
"   act('measuring spoke '+(lastIdx===null?'':lastIdx)+'...','t-nav',f.ts_ms);\n"
"  else if(f.to==='COMPUTE_ADJUSTMENTS')act('computing adjustments...','t-nav',f.ts_ms);\n"
"  else if(f.to==='VERIFY')act('verifying...','t-nav',f.ts_ms);\n"
"  render();return;}\n"
" if(k==='WAIT_ISSUED'){\n"
"  dbg('wait #'+f.wait.wait_id+' '+f.wait.kind+' index '+f.wait.target_index,'t-warn',f.ts_ms);\n"
"  lastIdx=f.wait.target_index;\n"
"  act(waitLine(f.wait),'t-warn',f.ts_ms);\n"
"  /* The wait_id must come from the snapshot, so ask - once per wait, not per transition. */\n"
"  send({cmd:'GET_CURRENT_STATE'});return;}\n"
" if(k==='MEASUREMENT_RESULT'){\n"
"  var t=f.channel==='TENSION'\n"
"   ?('spoke '+f.index+' measured: '+f.selected_frequency_hz+' Hz, '+f.tension_n+' N'+\n"
"     (f.status==='valid'?'':' - '+f.status))\n"
"   :('rim '+f.index+' read: lat '+f.lateral_mm+' mm, rad '+f.radial_mm+' mm');\n"
"  act(t,f.status==='valid'?'t-good':(f.status==='suspect'?'t-warn':'t-bad'),f.ts_ms);\n"
"  dbg(t+(f.reason&&f.reason!=='NONE'?' ['+f.reason+']':''),'',f.ts_ms);return;}\n"
" if(k==='TERMINAL_RESULT'){act('run finished: '+f.result,'t-good',f.ts_ms);\n"
"  dbg('TERMINAL '+f.result,'t-good',f.ts_ms);send({cmd:'GET_CURRENT_STATE'});return;}\n"
" if(k==='NAVIGATION'){dbg('nav '+f.target_kind+' '+f.index+' '+f.outcome,'t-nav',f.ts_ms);return;}\n"
" if(k==='INTENT_REJECTED'){act('refused: '+f.intent+' '+f.verdict,'t-bad',f.ts_ms);\n"
"  dbg('rejected '+f.intent+': '+f.verdict,'t-bad',f.ts_ms);return;}\n"
" if(k==='LOG'){dbg(f.text,'',f.ts_ms);return;}\n"
" dbg(k,'',f.ts_ms);}\n"

"function waitLine(w){\n"
" if(w.kind==='APPLY_ADJUSTMENT')\n"
"  return 'turn spoke '+w.target_index+' by '+w.display_turns_rev+' rev';\n"
" if(w.kind==='ENTER_RUNOUT')return 'enter dial readings for rim index '+w.target_index;\n"
" if(w.kind==='CONFIRM_SPOKE0_AT_STATION')return 'put spoke 0 at the '+w.station+' station';\n"
" return 'position spoke '+w.target_index+' at the '+w.station+' station';}\n"

/* ---- phase captions -------------------------------------------------------------------
   Plain language for the states an operator can be sitting in front of. Names the
   firmware uses stay visible in the Machine state card and the protocol feed. */
"var BUSY={MEASURE_WHEEL_STATE:['READING WHEEL','Sampling the rim.'],\n"
" POSITION:['POSITIONING','Working out the next target.'],\n"
" POSITION_TO_SPOKE:['POSITIONING','Working out the next target.'],\n"
" MEASURE_SPOKE_TENSION:['MEASURING','Capturing and analysing the spoke vibration.'],\n"
" READ_RUNOUT:['READING RUNOUT','Collecting the dial readings.'],\n"
" CHECK_SOLVER_ADMISSION:['CHECKING','Deciding whether the solve may run.'],\n"
" REMEASURE_GAPS:['RE-MEASURING','Filling the gaps the solver needs.'],\n"
" COMPUTE_ADJUSTMENTS:['COMPUTING','Solving for the spoke adjustments.'],\n"
" COMPUTE_TARGETS:['COMPUTING','Turning the solve into nipple turns.'],\n"
" APPLY_ADJUSTMENT:['APPLYING','Waiting on the adjustment.'],\n"
" VERIFY:['VERIFYING','Re-checking the wheel.'],\n"
" EVALUATE_CONVERGENCE:['EVALUATING','Deciding whether another cycle is needed.'],\n"
" INITIALIZE:['STARTING UP',''],BOOT:['STARTING UP','']};\n"

"function pillClass(s){if(s==='READY')return 'pill ok';if(s==='TERMINAL')return 'pill done';\n"
" if(s==='WAIT_FOR_OPERATOR')return 'pill warn';return 'pill run';}\n"

"function passLabel(){\n"
" if(!curState)return '';\n"
" var w=snap&&snap.active_wait;\n"
" if(w&&w.kind==='APPLY_ADJUSTMENT')return 'Adjustment pass';\n"
" if(w&&w.kind==='ENTER_RUNOUT')return 'Runout collection';\n"
" if(curState==='APPLY_ADJUSTMENT'||curState==='POSITION_TO_SPOKE'||curState==='VERIFY')\n"
"  return 'Adjustment pass';\n"
" if(curState==='READ_RUNOUT')return 'Runout collection';\n"
" if(curState==='TERMINAL')return 'Finished';\n"
" if(curState==='READY')return 'Ready';\n"
" return 'Measurement pass';}\n"

"function startTick(){if(tick)return;\n"
" tick=setInterval(function(){var e=el('elapsed');\n"
"  if(!e){clearInterval(tick);tick=null;return;}\n"
"  e.textContent=((Date.now()-busySince)/1000).toFixed(1)+' s';},100);}\n"
"function stopTick(){if(tick){clearInterval(tick);tick=null;}}\n"

"function render(){\n"
" var s=snap;\n"
" el('st').innerHTML='';\n"
" el('st').appendChild(mk('span',pillClass(curState),curState||'-'));\n"
" el('se').textContent=s?(s.session_active?'active':'idle'):'-';\n"
" el('cy').textContent=s?(s.cycle_index+' (run '+s.cycles_run+')'):'-';\n"
" el('lr').textContent=(s&&s.last_known_result)||'-';\n"
" el('b-start').disabled=!s||curState!=='READY'||!!pending;\n"
" el('b-abort').disabled=!s||!s.session_active||!!pending;\n"

" el('pass').textContent=passLabel();\n"
" var idx=(s&&s.active_wait&&s.active_wait.target_index!==undefined&&\n"
"  s.active_wait.target_index!==null)?s.active_wait.target_index:lastIdx;\n"
" if(idx!==null&&idx!==undefined&&nSpokes){\n"
"  el('pos').textContent='spoke '+idx+' of '+nSpokes;\n"
"  el('barfill').style.width=Math.min(100,(idx/nSpokes)*100)+'%';\n"
" }else if(idx!==null&&idx!==undefined){el('pos').textContent='spoke '+idx;}\n"
" else{el('pos').textContent='';}\n"

" var p=el('prompt'),a=el('answer'),card=el('opcard');\n"
" p.innerHTML='';a.innerHTML='';\n"
" var w=s&&s.active_wait;\n"

" if(pending){card.className='card busy';\n"
"  p.appendChild(mk('div','tag b','SENDING'));\n"
"  p.appendChild(mk('p','say',verb(pending.intent)+' - waiting for the machine to accept it.'));\n"
"  var sh=mk('div','shim');sh.appendChild(mk('i'));p.appendChild(sh);\n"
"  stopTick();return;}\n"

" if(flash){card.className='card '+(flash.tag==='g'?'good':'err');\n"
"  p.appendChild(mk('div','tag '+flash.tag,flash.title));\n"
"  p.appendChild(mk('p','say',flash.say));stopTick();return;}\n"

" if(w){card.className='card wait';stopTick();\n"
"  p.appendChild(mk('div','tag w','WAITING FOR YOU'));\n"
"  var big=mk('div','big');\n"
"  if(w.kind==='APPLY_ADJUSTMENT'){var rev=w.display_turns_rev;\n"
"   big.appendChild(mk('span','',(rev>=0?'+':'')+rev));big.appendChild(mk('span','u','rev'));\n"
"   p.appendChild(big);\n"
"   p.appendChild(mk('span','dir '+(rev>=0?'t':'l'),rev>=0?'TIGHTEN':'LOOSEN'));\n"
"  }else if(w.target_index!==undefined&&w.target_index!==null){\n"
"   var rim=(w.kind==='POSITION_TO_RIM_INDEX'||w.kind==='ENTER_RUNOUT');\n"
"   big.appendChild(mk('span','',w.target_index));\n"
"   big.appendChild(mk('span','u',rim?'rim index':'spoke'));p.appendChild(big);}\n"
"  p.appendChild(mk('p','say',describe(w)));\n"
"  /* Every answer echoes the wait_id from this snapshot - SPEC 12.3. */\n"
"  if(w.expected_intent==='SUBMIT_RUNOUT'){\n"
"   var g=mk('div','fields'),d1=mk('div'),d2=mk('div');\n"
"   d1.appendChild(mk('label','fl','lateral mm'));d2.appendChild(mk('label','fl','radial mm'));\n"
"   var i1=mk('input'),i2=mk('input');\n"
"   i1.id='lat';i1.type='number';i1.step='0.01';i1.inputMode='decimal';i1.placeholder='0.00';\n"
"   i2.id='rad';i2.type='number';i2.step='0.01';i2.inputMode='decimal';i2.placeholder='0.00';\n"
"   d1.appendChild(i1);d2.appendChild(i2);g.appendChild(d1);g.appendChild(d2);a.appendChild(g);\n"
"   var b=mk('button','go wide','Submit runout');\n"
"   b.onclick=function(){submit('SUBMIT_RUNOUT',w.wait_id,\n"
"    {lateral_mm:parseFloat(el('lat').value||'0'),radial_mm:parseFloat(el('rad').value||'0')});};\n"
"   a.appendChild(b);\n"
"  }else{\n"
"   var c=mk('button','go wide',\n"
"    w.expected_intent==='CONFIRM_ADJUSTMENT_DONE'?'Adjustment applied':'Positioned');\n"
"   c.onclick=function(){submit(w.expected_intent,w.wait_id);};a.appendChild(c);}\n"
"  return;}\n"

" var b2=BUSY[curState];\n"
" if(b2&&s&&s.session_active){card.className='card busy';\n"
"  if(!busySince)busySince=Date.now();\n"
"  p.appendChild(mk('div','tag b',b2[0]));\n"
"  p.appendChild(mk('p','say',b2[1]));\n"
"  var sh2=mk('div','shim');sh2.appendChild(mk('i'));p.appendChild(sh2);\n"
"  var e=mk('div','el','0.0 s');e.id='elapsed';p.appendChild(e);\n"
"  startTick();return;}\n"

" stopTick();card.className='card';\n"
" if(curState==='TERMINAL'){p.appendChild(mk('div','tag d','RUN FINISHED'));\n"
"  p.appendChild(mk('p','say',(s&&s.last_known_result)||'The run has ended.'));return;}\n"
" if(curState==='READY'){p.appendChild(mk('div','tag g','READY'));\n"
"  p.appendChild(mk('p','say','Press Start truing to begin a session.'));return;}\n"
" p.appendChild(mk('div','tag d','STANDING BY'));\n"
" p.appendChild(mk('p','say','Nothing to confirm right now.'));}\n"

"function describe(w){switch(w.kind){\n"
" case 'CONFIRM_SPOKE0_AT_STATION':\n"
"  return 'Rotate the wheel so SPOKE 0 is at the '+w.station+' station, then confirm.';\n"
" case 'POSITION_TO_SPOKE':\n"
"  return 'Rotate the wheel so SPOKE '+w.target_index+' is at the '+w.station+' station.';\n"
" case 'POSITION_TO_RIM_INDEX':\n"
"  return 'Rotate the wheel so RIM INDEX '+w.target_index+' is at the '+w.station+' station.';\n"
" case 'POSITION_TO_RIM_ANGLE':\n"
"  return 'Rotate the wheel so rim angle '+w.target_angle_rad+' rad is at the '+w.station+\n"
"   ' station.';\n"
" case 'ENTER_RUNOUT':\n"
"  return 'Read both dials for RIM INDEX '+w.target_index+' and enter them.';\n"
" case 'APPLY_ADJUSTMENT':\n"
"  return 'Turn the nipple on SPOKE '+w.target_index+' at the '+w.station+' station.';\n"
" default: return w.kind+' (index '+w.target_index+', station '+w.station+')';}}\n"

"el('b-start').onclick=function(){send({cmd:'START_TRUING'});};\n"
"el('b-abort').onclick=function(){send({cmd:'ABORT'});};\n"
"el('b-refresh').onclick=function(){send({cmd:'GET_CURRENT_STATE'});\n"
" send({cmd:'GET_CURRENT_CYCLE_PROVENANCE'});};\n"
"el('b-prov').onclick=function(){send({cmd:'GET_CURRENT_CYCLE_PROVENANCE'});};\n"
"el('b-dbg').onclick=function(){var d=el('dbg'),a=el('act');\n"
" var on=d.className.indexOf('hide')>=0;\n"
" d.className=on?'feed':'feed hide';a.className=on?'feed hide':'feed';\n"
" this.textContent=on?'Show activity':'Show protocol';};\n"
"render();connect();\n"
"</script></body></html>\n";

#endif /* TRUING_WEB_UI_H */
