/**
 * @file web_ui.h
 * The SPEC §12.1 web UI, served from flash as one self-contained page.
 *
 * Compiled in as a C string rather than embedded as a binary: none of the ESP-IDF
 * binary-embedding routes works under this toolchain, because PlatformIO parses CMake
 * for sources and flags but builds with SCons, so the assembly file that EMBED_FILES
 * and target_add_binary_data generate through a CMake custom command is never produced
 * (the same finding as the acoustic fixtures, recorded in src/CMakeLists.txt).
 *
 * No external assets, no CDN, no build step: the board is an isolated access point with
 * no route to the internet, so anything the page does not carry itself cannot load.
 *
 * The page is a STATE MIRROR, not a data processor (SPEC §12.2). It renders what the
 * firmware reports and never computes machine state of its own:
 *
 *   - `active_wait` and its wait_id come ONLY from a state snapshot, never from a
 *     WAIT_ISSUED event, because the wait_id is the SPEC §12.3 safety contract.
 *   - the phase caption is driven off STATE_TRANSITION events, which is still mirroring
 *     (the caption is the `to` field the firmware sent) and is what keeps this to one
 *     snapshot query per wait instead of one per transition.
 *
 * THREE AUDIENCES, three tabs. An operator needs to know what to do next and whether the
 * machine heard them; an evaluator needs to know what produced a number and how far to
 * trust it; a developer needs the frames. Mixing those on one screen is what made the
 * earlier page read as a debug console. So: Operator leads, Run details translates the
 * provenance document into sentences, Diagnostics keeps every raw enum, frame and counter.
 *
 * TRANSLATION, NOT CONCEALMENT. Internal names are given a plain-language meaning and the
 * original is still shown next to it. `CONVERGED_GEOMETRIC_ONLY` becomes "Geometry target
 * reached" with the caveat that tension was not verification-grade, because an evaluator
 * who is not told that has been misled, and an operator who is only shown the enum has
 * been told nothing.
 *
 * Timing is honest. A measurement is ~3.85 s of DSP while its ack returns in ~50 ms, so
 * "working" is a state of its own with a real elapsed counter, never a bar filling toward
 * a guess.
 *
 * Single quotes throughout so the C string literal needs no escaping.
 */
#ifndef TRUING_WEB_UI_H
#define TRUING_WEB_UI_H

static const char TRUING_WEB_UI_HTML[] =
"<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1,viewport-fit=cover'>\n"
"<title>Truing Machine</title><style>\n"
":root{--bg:#0f1115;--card:#171a21;--card2:#1e222b;--fg:#e9ecf1;--dim:#8b93a1;\n"
" --line:#282d38;--ok:#4fc08d;--warn:#e8a13f;--bad:#e85c5c;--run:#54a8e0;--pad:14px}\n"
"*{box-sizing:border-box}html{-webkit-text-size-adjust:100%}\n"
"body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.55 -apple-system,\n"
" BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;\n"
" padding-bottom:env(safe-area-inset-bottom)}\n"
".mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}\n"
"header{position:sticky;top:0;z-index:5;background:#0f1115ee;\n"
" border-bottom:1px solid var(--line)}\n"
".hrow{display:flex;gap:10px;align-items:center;padding:10px var(--pad) 6px}\n"
"h1{font-size:15px;margin:0;font-weight:650;letter-spacing:.01em}\n"
"#dot{width:9px;height:9px;border-radius:50%;background:var(--bad);flex:none;\n"
" box-shadow:0 0 0 3px #e85c5c22}\n"
"#dot.up{background:var(--ok);box-shadow:0 0 0 3px #4fc08d22}\n"
"#ident{margin-left:auto;font-size:11px;color:var(--dim);text-align:right;line-height:1.35}\n"
".tabs{display:flex;gap:2px;padding:0 var(--pad)}\n"
".tabs button{background:none;border:0;border-bottom:2px solid transparent;color:var(--dim);\n"
" font:inherit;font-size:12px;padding:7px 11px;cursor:pointer;min-height:0}\n"
".tabs button.on{color:var(--fg);border-bottom-color:var(--run)}\n"
".tabs button:hover{color:var(--fg)}\n"
"main{display:grid;grid-template-columns:minmax(340px,1.05fr) minmax(320px,.95fr);\n"
" gap:var(--pad);padding:var(--pad);align-items:start}\n"
"@media(max-width:880px){main{grid-template-columns:1fr;padding:10px;gap:10px}}\n"
".col{display:flex;flex-direction:column;gap:var(--pad);min-width:0}\n"
"@media(max-width:880px){.col{gap:10px}}\n"
".card{background:var(--card);border:1px solid var(--line);border-radius:10px;\n"
" padding:13px 15px;min-width:0}\n"
".card>h2{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:var(--dim);\n"
" margin:0 0 11px;font-weight:650;display:flex;align-items:center;gap:8px}\n"
".card>h2 .sp{margin-left:auto}\n"

/* headline status */
"#status{padding:15px}\n"
"#status.wait{border-color:var(--warn);box-shadow:0 0 0 1px #e8a13f33,0 6px 22px #0006}\n"
"#status.busy{border-color:var(--run);box-shadow:0 0 0 1px #54a8e033}\n"
"#status.good{border-color:var(--ok);box-shadow:0 0 0 1px #4fc08d33}\n"
"#status.err{border-color:var(--bad);box-shadow:0 0 0 1px #e85c5c33}\n"
".head{font-size:19px;font-weight:650;letter-spacing:-.01em;margin:0 0 3px}\n"
".head.w{color:var(--warn)}.head.b{color:var(--run)}.head.g{color:var(--ok)}\n"
".head.e{color:var(--bad)}\n"
".sub{color:var(--dim);margin:0;font-size:13px}\n"
".enum{font-size:10px;color:#5d6675;letter-spacing:.06em;margin-top:7px}\n"
".big{font:650 clamp(32px,10vw,48px)/1.06 ui-monospace,SFMono-Regular,Menlo,Consolas,\n"
" monospace;letter-spacing:-.02em;display:flex;align-items:baseline;gap:9px;margin:9px 0 4px}\n"
".big .u{font-size:13px;font-weight:600;color:var(--dim);letter-spacing:.05em;\n"
" font-family:inherit}\n"
".dir{display:inline-block;font-size:11px;font-weight:700;letter-spacing:.09em;\n"
" padding:3px 9px;border-radius:999px;margin-bottom:7px}\n"
".dir.t{background:#2a4a38;color:#8fe0b4}.dir.l{background:#4a3a2a;color:#e8c48f}\n"
".shim{height:3px;border-radius:2px;margin:11px 0 9px;background:#0d0f13;overflow:hidden}\n"
".shim i{display:block;height:100%;width:34%;border-radius:2px;background:var(--run);\n"
" animation:sl 1.1s ease-in-out infinite}\n"
"@keyframes sl{0%{transform:translateX(-100%)}100%{transform:translateX(390%)}}\n"
".el{font-size:12px;color:var(--dim);font-variant-numeric:tabular-nums}\n"
".step-of{font-size:11px;letter-spacing:.1em;text-transform:uppercase;color:var(--dim);\n"
" margin-bottom:2px}\n"

/* stepper */
".stp{display:flex;flex-direction:column;gap:1px}\n"
".stp>div{display:flex;gap:10px;align-items:baseline;padding:5px 7px;border-radius:6px;\n"
" font-size:13px}\n"
".stp>div.now{background:#54a8e014;color:var(--fg)}\n"
".stp>div.done{color:var(--dim)}.stp>div.todo{color:#5d6675}\n"
".stp .mk{width:16px;flex:none;text-align:center;font-size:11px}\n"
".stp .rt{margin-left:auto;font-size:11px;color:var(--dim);font-variant-numeric:tabular-nums}\n"
".stp>div.now .mk{color:var(--run)}.stp>div.done .mk{color:var(--ok)}\n"

/* measurement */
".meas{display:grid;grid-template-columns:1fr 1fr;gap:11px}\n"
".meas .lbl{font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:var(--dim)}\n"
".meas .val{font:650 22px/1.2 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}\n"
".note{font-size:12px;color:var(--dim);margin:11px 0 0;padding-top:10px;\n"
" border-top:1px solid var(--line)}\n"
".flag{display:inline-block;font-size:10px;font-weight:700;letter-spacing:.09em;\n"
" padding:2px 8px;border-radius:999px;background:#4a3a1f;color:#e8c48f}\n"
".flag.ok{background:#1f4636;color:#8fe0b4}.flag.bad{background:#4a2626;color:#f0a6a6}\n"

/* run details */
".dl{display:grid;grid-template-columns:1fr;gap:12px}\n"
".dl .k{font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:var(--dim)}\n"
".dl .v{font-size:14px}\n"
".dl .x{font-size:12px;color:var(--dim);margin-top:2px}\n"
".warnbox{border:1px solid #6d4a1f;background:#3a2c14;border-radius:8px;padding:11px 13px;\n"
" font-size:13px}\n"
".warnbox b{color:#e8c48f}\n"

/* controls */
"button{font:inherit;background:var(--card2);color:var(--fg);border:1px solid var(--line);\n"
" border-radius:8px;padding:9px 13px;cursor:pointer;min-height:40px}\n"
"button:hover:not(:disabled){background:#262b36;border-color:#3a414f}\n"
"button:active:not(:disabled){transform:translateY(1px)}\n"
"button:disabled{opacity:.32;cursor:not-allowed}\n"
"button.go{background:#1f5540;border-color:#2b6d52;color:#d8f5e6;font-weight:650}\n"
"button.go:hover:not(:disabled){background:#256549}\n"
"button.stop{background:#54282a;border-color:#6d3538;color:#f6dada}\n"
"button.wide{width:100%;min-height:54px;font-size:16px;font-weight:700;letter-spacing:.02em}\n"
"button.tiny{min-height:0;padding:3px 9px;font-size:10px;letter-spacing:.07em;\n"
" text-transform:uppercase}\n"
".row{display:flex;gap:8px;flex-wrap:wrap}.row>button{flex:1 1 auto}\n"
".sep{border:0;border-top:1px solid var(--line);margin:13px 0}\n"
"input{font:inherit;background:#0d0f13;color:var(--fg);border:1px solid var(--line);\n"
" border-radius:8px;padding:10px;width:100%;min-height:44px}\n"
".fields{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px}\n"
".fl{font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:var(--dim);\n"
" display:block;margin-bottom:4px}\n"
"#hint{font-size:12px;color:var(--dim);margin-top:9px;min-height:1em}\n"
"#hint.bad{color:var(--bad)}\n"

/* feeds + diagnostics */
".kv{display:grid;grid-template-columns:auto 1fr;gap:7px 14px;margin:0;font-size:13px}\n"
".kv dt{color:var(--dim)}.kv dd{margin:0;word-break:break-word;text-align:right}\n"
".feed{height:min(46vh,420px);overflow-y:auto;background:#0d0f13;border-radius:8px;\n"
" padding:6px;border:1px solid #1b1f28}\n"
"@media(max-width:880px){.feed{height:34vh}}\n"
".feed>div{padding:4px 7px;border-radius:5px;display:flex;gap:9px;white-space:pre-wrap;\n"
" word-break:break-word;font-size:13px}\n"
".feed>div:nth-child(odd){background:#ffffff05}\n"
".feed .ts{color:#5d6675;flex:none;font-variant-numeric:tabular-nums;font-size:11px}\n"
"#dbg>div{font-size:11px;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}\n"
".t-ack{color:var(--dim)}.t-bad{color:var(--bad)}.t-good{color:var(--ok)}\n"
".t-warn{color:var(--warn)}.t-nav{color:var(--run)}.t-pend{color:var(--dim);opacity:.7}\n"
"pre{background:#0d0f13;border:1px solid #1b1f28;border-radius:8px;padding:10px;\n"
" font-size:11px;line-height:1.45;max-height:300px;overflow:auto;margin:0;\n"
" font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}\n"
"pre.empty{color:var(--dim)}\n"
".hide{display:none}\n"
"</style></head><body>\n"

"<header>\n"
" <div class='hrow'><span id='dot'></span><h1>Truing Machine</h1>\n"
"  <div id='ident'>connecting</div></div>\n"
" <div class='tabs'>\n"
"  <button id='tab-op' class='on'>Operator</button>\n"
"  <button id='tab-run'>Run details</button>\n"
"  <button id='tab-dev'>Diagnostics</button>\n"
" </div>\n"
"</header>\n"

"<main id='v-op'>\n"
" <div class='col'>\n"
"  <div class='card' id='status'>\n"
"   <div id='statusbody'></div>\n"
"   <div id='answer'></div>\n"
"   <hr class='sep'>\n"
"   <div class='row'>\n"
"    <button class='go' id='b-start'>Start truing</button>\n"
"    <button class='stop' id='b-abort'>Abort</button>\n"
"    <button id='b-refresh'>Resync</button>\n"
"   </div>\n"
"   <div id='hint'></div>\n"
"  </div>\n"
"  <div class='card'><h2>Session progress</h2><div class='stp' id='stepper'></div></div>\n"
"  <div class='card' id='lastcard'><h2>Latest measurement</h2><div id='last'></div></div>\n"
" </div>\n"
" <div class='col'>\n"
"  <div class='card'><h2>Activity</h2><div class='feed' id='act'></div></div>\n"
" </div>\n"
"</main>\n"

"<main id='v-run' class='hide'>\n"
" <div class='col'>\n"
"  <div class='card'><h2>What produced this run</h2><div class='dl' id='rundl'></div></div>\n"
" </div>\n"
" <div class='col'>\n"
"  <div class='card'><h2>Outcome</h2><div id='outcome'></div></div>\n"
"  <div class='card'><h2>Technical detail<button class='tiny sp' id='b-raw'>Show raw</button></h2>\n"
"   <div id='techdl' class='dl'></div>\n"
"   <pre id='prov' class='empty hide'>Press Resync to fetch the provenance document.</pre>\n"
"  </div>\n"
" </div>\n"
"</main>\n"

"<main id='v-dev' class='hide'>\n"
" <div class='col'>\n"
"  <div class='card'><h2>Machine state</h2>\n"
"   <dl class='kv'><dt>state</dt><dd id='st' class='mono'>-</dd>\n"
"   <dt>session</dt><dd id='se'>-</dd>\n"
"   <dt>cycle</dt><dd id='cy'>-</dd>\n"
"   <dt>last result</dt><dd id='lr' class='mono'>-</dd>\n"
"   <dt>last reason</dt><dd id='lrr' class='mono'>-</dd></dl>\n"
"  </div>\n"
"  <div class='card'><h2>Build identity</h2>\n"
"   <dl class='kv'><dt>board</dt><dd id='i-board' class='mono'>-</dd>\n"
"   <dt>firmware</dt><dd id='i-fw' class='mono'>-</dd>\n"
"   <dt>build</dt><dd id='i-build' class='mono'>-</dd>\n"
"   <dt>ui hash</dt><dd id='i-ui' class='mono'>-</dd>\n"
"   <dt>ap ssid</dt><dd id='i-ssid' class='mono'>-</dd>\n"
"   <dt>uptime</dt><dd id='i-up' class='mono'>-</dd></dl>\n"
"  </div>\n"
" </div>\n"
" <div class='col'>\n"
"  <div class='card'><h2>Protocol</h2><div class='feed' id='dbg'></div></div>\n"
" </div>\n"
"</main>\n"

"<script>\n"
"var ws=null,snap=null,prov=null,ident=null,seq=0,pending=null,curState=null;\n"
"var nSpokes=0,lastIdx=null,lastMeas=null,busySince=0,tick=null,flash=null,tab='op';\n"
/* Owned here rather than read back off the element's class, so the visible state has one
   source and does not depend on what the markup happened to start with. */
"var rawOpen=false;\n"
"function renderRaw(){el('prov').className=rawOpen?'':'hide';\n"
" el('b-raw').textContent=rawOpen?'Hide raw':'Show raw';}\n"
"function el(id){return document.getElementById(id);}\n"
"function mk(t,c,x){var e=document.createElement(t);if(c)e.className=c;\n"
" if(x!==undefined)e.textContent=x;return e;}\n"
"function put(p,t,c,x){return p.appendChild(mk(t,c,x));}\n"
"function hms(ms){var s=ms/1000,m=Math.floor(s/60);\n"
" return m+':'+(s-m*60).toFixed(1).padStart(4,'0');}\n"

/* ---- translations ---------------------------------------------------------------------
   Every internal name that reaches the operator surface gets a meaning. The original is
   still printed beside it, small: translating is not the same as hiding, and an evaluator
   needs to be able to map what they read back to the firmware. */
"var TERM={\n"
" CONVERGED:['Truing complete',\n"
"  'The wheel met every configured tolerance, tension included.','g'],\n"
" CONVERGED_GEOMETRIC_ONLY:['Geometry target reached',\n"
"  'The wheel geometry met the configured tolerance. Tension was not treated as '+\n"
"  'verification-grade for this session, so this is a geometry-only result.','g'],\n"
" ABORT_OPERATOR:['Run stopped','The operator cancelled the session.','d'],\n"
" ABORT_NO_PROGRESS:['Run stopped - no further progress',\n"
"  'Successive cycles stopped improving the wheel, so the machine stopped rather than '+\n"
"  'keep adjusting.','e'],\n"
" ABORT_MAX_CYCLES:['Run stopped - cycle limit',\n"
"  'The configured maximum number of truing cycles was reached.','e'],\n"
" ABORT_UNSAFE_ADJUSTMENT:['Run stopped - unsafe adjustment',\n"
"  'The computed correction exceeded the configured safety bound and was refused.','e'],\n"
" ABORT_NO_MODEL:['Run stopped - no usable model',\n"
"  'No influence model was available for this wheel, so no correction could be computed.',\n"
"  'e'],\n"
" ABORT_PARTIAL_STATE:['Run stopped - incomplete measurements',\n"
"  'Too much of the wheel state was missing or suspect for the solver to be trusted.','e']};\n"

"var REASON={\n"
" MEAN_TENSION_MODEL_UNAVAILABLE:['Mean-tension correction unavailable',\n"
"  'This wheel model does not support trusted mean-tension targeting, so the solver ran '+\n"
"  'in geometry-only mode.'],\n"
" TENSION_NOT_VERIFICATION_GRADE:['Tension not verification-grade',\n"
"  'Tension readings were taken but are not trusted enough to count toward convergence.'],\n"
" PROVISIONAL_MODE_ID:['Provisional measurement',\n"
"  'The frequency is usable for the current research workflow, but the vibration mode has '+\n"
"  'not yet been fully validated (SPEC 4.4.1).'],\n"
" LOW_SNR:['Weak signal','The pluck was too quiet against the noise floor to trust.'],\n"
" NO_ONSET_DETECTED:['No pluck detected','Nothing that looks like a pluck was captured.'],\n"
" AMBIGUOUS_PEAK:['Ambiguous peak',\n"
"  'More than one candidate frequency was equally plausible.'],\n"
" FREQ_OUT_OF_RANGE:['Frequency out of range',\n"
"  'The detected frequency falls outside the band this wheel class expects.'],\n"
" CALIBRATION_MISSING:['Calibration missing',\n"
"  'The tension model for this wheel has not been provisioned.'],\n"
" STALE_INTENT:['Already answered','That wait had already been answered.'],\n"
" CANCELLED:['Cancelled','The operation was cancelled.'],\n"
" PARTIAL_WHEEL_STATE:['Incomplete wheel state',\n"
"  'Some spokes or rim positions have no usable measurement.'],\n"
" CAPTURE_OVERRUN:['Capture overrun','Audio samples were lost during the capture.']};\n"

"var BUSY={MEASURE_WHEEL_STATE:['Reading wheel state','Collecting the current rim shape.'],\n"
" POSITION:['Positioning','Working out the next target.'],\n"
" POSITION_TO_SPOKE:['Positioning','Working out the next target.'],\n"
" MEASURE_SPOKE_TENSION:['Measuring','Capturing and analysing the spoke vibration.'],\n"
" READ_RUNOUT:['Reading runout','Collecting the dial readings.'],\n"
" CHECK_SOLVER_ADMISSION:['Checking measurements',\n"
"  'Deciding whether there is enough good data to solve.'],\n"
" REMEASURE_GAPS:['Re-measuring','Filling the gaps the solver needs.'],\n"
" COMPUTE_ADJUSTMENTS:['Computing the plan','Solving for the spoke adjustments.'],\n"
" COMPUTE_TARGETS:['Computing the plan','Turning the solve into nipple turns.'],\n"
" APPLY_ADJUSTMENT:['Applying','Waiting on the adjustment.'],\n"
" VERIFY:['Verifying','Re-checking the wheel against tolerance.'],\n"
" EVALUATE_CONVERGENCE:['Evaluating','Deciding whether another cycle is needed.'],\n"
" INITIALIZE:['Starting up','Establishing the wheel reference.'],\n"
" BOOT:['Starting up','']};\n"

/* The stepper is the real workflow, grouped. Nothing here is invented: each entry lists
   the states the firmware actually passes through for that stage. */
"var STAGES=[['Initialise',['BOOT','INITIALIZE','READY']],\n"
" ['Measure spokes',['MEASURE_WHEEL_STATE','POSITION','MEASURE_SPOKE_TENSION']],\n"
" ['Read runout',['READ_RUNOUT']],\n"
" ['Compute plan',['CHECK_SOLVER_ADMISSION','REMEASURE_GAPS','COMPUTE_ADJUSTMENTS',\n"
"  'COMPUTE_TARGETS']],\n"
" ['Apply changes',['POSITION_TO_SPOKE','APPLY_ADJUSTMENT']],\n"
" ['Verify',['VERIFY','EVALUATE_CONVERGENCE']]];\n"

"function stageOf(st){\n"
" for(var i=0;i<STAGES.length;i++)if(STAGES[i][1].indexOf(st)>=0)return i;\n"
" return -1;}\n"

/* ---- feeds ---------------------------------------------------------------------------- */
"function feed(which,text,cls,ts){var d=mk('div');\n"
" d.appendChild(mk('span','ts',ts===undefined?'':hms(ts)));\n"
" d.appendChild(mk('span',cls||'',text));\n"
" var L=el(which);var stick=L.scrollTop+L.clientHeight>=L.scrollHeight-24;\n"
" L.appendChild(d);while(L.childNodes.length>300){L.removeChild(L.firstChild);}\n"
" if(stick)L.scrollTop=L.scrollHeight;return d;}\n"
"function act(t,c,ts){return feed('act',t,c,ts);}\n"
"function dbg(t,c,ts){return feed('dbg',t,c,ts);}\n"

"function send(o){if(!ws||ws.readyState!==1){hint('not connected',1);return 0;}\n"
" o.seq=++seq;ws.send(JSON.stringify(o));dbg('-> '+JSON.stringify(o),'t-ack');return o.seq;}\n"
"function hint(t,bad){var h=el('hint');h.textContent=t||'';h.className=bad?'bad':'';}\n"

/* ---- command lifecycle ----------------------------------------------------------------- */
"function submit(intent,waitId,extra){\n"
" if(pending)return;\n"
" var o={cmd:intent,wait_id:waitId};\n"
" if(extra)for(var k in extra)o[k]=extra[k];\n"
" var s=send(o);if(!s)return;\n"
" pending={seq:s,waitId:waitId,intent:intent,\n"
"  node:act('you: '+verb(intent)+' (sending)','t-pend')};\n"
" pending.timer=setTimeout(function(){\n"
"  if(!pending)return;\n"
"  pending.node.lastChild.textContent='you: '+verb(pending.intent)+' - NO REPLY';\n"
"  pending.node.lastChild.className='t-bad';\n"
"  hint('No reply from the machine after 6 s. Still connected? Press Resync.',1);\n"
"  pending=null;render();},6000);\n"
" render();}\n"
"function verb(i){\n"
" if(i==='CONFIRM_POSITIONED')return 'positioned';\n"
" if(i==='CONFIRM_ADJUSTMENT_DONE')return 'adjustment applied';\n"
" if(i==='SUBMIT_RUNOUT')return 'runout entered';\n"
" return i;}\n"

"function loadIdent(){\n"
" try{var x=new XMLHttpRequest();x.open('GET','/id?t='+Date.now(),true);\n"
"  x.onload=function(){try{ident=JSON.parse(x.responseText);renderIdent();}catch(e){}};\n"
"  x.send();}catch(e){}}\n"
"function renderIdent(){\n"
" if(!ident)return;\n"
" el('ident').textContent=ident.board+' \\u00b7 fw '+ident.firmware+'\\n'+\n"
"  'build '+ident.build+' \\u00b7 ui '+ident.ui;\n"
" el('ident').style.whiteSpace='pre';\n"
" el('i-board').textContent=ident.board;el('i-fw').textContent=ident.firmware;\n"
" el('i-build').textContent=ident.build;el('i-ui').textContent=ident.ui;\n"
" el('i-ssid').textContent=ident.ssid;\n"
" el('i-up').textContent=ident.uptime_s+' s';}\n"

"function connect(){\n"
" ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws');\n"
" ws.onopen=function(){el('dot').className='up';\n"
"  act('connected','t-good');loadIdent();\n"
"  send({cmd:'GET_CURRENT_STATE'});send({cmd:'GET_CURRENT_CYCLE_PROVENANCE'});};\n"
" ws.onclose=function(){el('dot').className='';\n"
"  act('connection lost - retrying','t-warn');\n"
"  if(pending){clearTimeout(pending.timer);pending=null;}\n"
"  setTimeout(connect,1500);};\n"
" ws.onmessage=function(m){var f;try{f=JSON.parse(m.data);}catch(e){return;}handle(f);};}\n"

"function handle(f){\n"
" if(f.t==='state'){snap=f;curState=f.current_state;render();return;}\n"
" if(f.t==='provenance'){prov=f;\n"
"  el('prov').textContent=JSON.stringify(f,null,1);renderRaw();\n"
"  if(f.wheel_state_summary&&f.wheel_state_summary.n_spokes)\n"
"   nSpokes=f.wheel_state_summary.n_spokes;\n"
"  dbg('provenance '+JSON.stringify(f).length+' bytes','t-ack');renderRun();render();return;}\n"
" if(f.t==='ack'){onAck(f);return;}\n"
" if(f.t==='event')onEvent(f);}\n"

"function onAck(f){\n"
" var what=f.intent||f.cmd_kind;\n"
" dbg('ack seq '+f.seq+' '+what+' '+(f.accepted?'accepted':\n"
"  ('REJECTED '+(f.verdict||f.wire))),f.accepted?'t-ack':'t-bad');\n"
" if(pending&&f.seq===pending.seq){\n"
"  clearTimeout(pending.timer);\n"
"  if(f.accepted){\n"
"   pending.node.lastChild.textContent='you: '+verb(pending.intent)+' - accepted';\n"
"   pending.node.lastChild.className='t-good';\n"
"   flash={c:'g',h:'Confirmed',s:'The machine has your answer.'};\n"
"   setTimeout(function(){flash=null;render();},900);\n"
"   pending=null;hint('');render();return;}\n"
"  var why=(f.verdict||f.wire)+(f.reason&&f.reason!=='NONE'?' / '+f.reason:'');\n"
"  pending.node.lastChild.textContent='you: '+verb(pending.intent)+' - REFUSED '+why;\n"
"  pending.node.lastChild.className='t-bad';\n"
"  pending=null;hint(explain(f.verdict,f.reason),1);\n"
"  send({cmd:'GET_CURRENT_STATE'});return;}\n"
" if(!f.accepted){act(what+' refused','t-bad');\n"
"  hint(explain(f.verdict,f.reason),1);send({cmd:'GET_CURRENT_STATE'});}}\n"

"function explain(v,r){\n"
" if(r&&r!=='NONE'&&REASON[r])return REASON[r][0]+' - '+REASON[r][1];\n"
" if(v==='REJECT_STATE')\n"
"  return 'Not available right now: the machine is in '+(curState||'?')+'.';\n"
" if(v==='REJECT_NO_ACTIVE_WAIT')return 'There is nothing waiting to be answered.';\n"
" if(v==='REJECT_STALE_INTENT')\n"
"  return 'That step was already answered; the machine has moved on.';\n"
" return v||'refused';}\n"

"function onEvent(f){var k=f.kind;\n"
" if(k==='STATE_TRANSITION'){dbg(f.from+' -> '+f.to,'',f.ts_ms);\n"
"  if(f.to!==curState)busySince=Date.now();\n"
"  curState=f.to;\n"
"  if(f.from==='WAIT_FOR_OPERATOR'&&snap)snap.active_wait=null;\n"
"  if(f.to==='MEASURE_SPOKE_TENSION')\n"
"   act('measuring spoke '+(lastIdx===null?'':lastIdx)+'...','t-nav',f.ts_ms);\n"
"  else if(f.to==='COMPUTE_ADJUSTMENTS')act('computing the plan...','t-nav',f.ts_ms);\n"
"  else if(f.to==='VERIFY')act('verifying...','t-nav',f.ts_ms);\n"
"  render();return;}\n"
" if(k==='WAIT_ISSUED'){\n"
"  dbg('wait #'+f.wait.wait_id+' '+f.wait.kind+' index '+f.wait.target_index,'t-warn',f.ts_ms);\n"
"  lastIdx=f.wait.target_index;act(waitLine(f.wait),'t-warn',f.ts_ms);\n"
"  send({cmd:'GET_CURRENT_STATE'});return;}\n"
" if(k==='MEASUREMENT_RESULT'){\n"
"  if(f.channel==='TENSION'){lastMeas=f;\n"
"   act('spoke '+f.index+' measured: '+f.selected_frequency_hz+' Hz, '+f.tension_n+' N'+\n"
"    (f.status==='valid'?'':' - '+f.status),\n"
"    f.status==='valid'?'t-good':(f.status==='suspect'?'t-warn':'t-bad'),f.ts_ms);}\n"
"  else{act('rim '+f.index+' read: lat '+f.lateral_mm+' mm, rad '+f.radial_mm+' mm',\n"
"   't-good',f.ts_ms);}\n"
"  dbg(JSON.stringify(f),'',f.ts_ms);render();return;}\n"
" if(k==='TERMINAL_RESULT'){act('run finished: '+f.result,'t-good',f.ts_ms);\n"
"  dbg('TERMINAL '+f.result,'t-good',f.ts_ms);\n"
"  send({cmd:'GET_CURRENT_STATE'});send({cmd:'GET_CURRENT_CYCLE_PROVENANCE'});return;}\n"
" if(k==='NAVIGATION'){dbg('nav '+f.target_kind+' '+f.index+' '+f.outcome,'t-nav',f.ts_ms);\n"
"  return;}\n"
" if(k==='INTENT_REJECTED'){act('refused: '+f.intent,'t-bad',f.ts_ms);\n"
"  dbg('rejected '+f.intent+': '+f.verdict,'t-bad',f.ts_ms);return;}\n"
" if(k==='LOG'){dbg(f.text,'',f.ts_ms);return;}\n"
" dbg(k,'',f.ts_ms);}\n"

"function waitLine(w){\n"
" if(w.kind==='APPLY_ADJUSTMENT')\n"
"  return 'turn spoke '+w.target_index+' by '+w.display_turns_rev+' rev';\n"
" if(w.kind==='ENTER_RUNOUT')return 'enter dial readings for rim index '+w.target_index;\n"
" if(w.kind==='CONFIRM_SPOKE0_AT_STATION')return 'put spoke 0 at the '+w.station+' station';\n"
" return 'position spoke '+w.target_index+' at the '+w.station+' station';}\n"

"function startTick(){if(tick)return;\n"
" tick=setInterval(function(){var e=el('elapsed');\n"
"  if(!e){clearInterval(tick);tick=null;return;}\n"
"  e.textContent=((Date.now()-busySince)/1000).toFixed(1)+' s elapsed';},100);}\n"
"function stopTick(){if(tick){clearInterval(tick);tick=null;}}\n"

/* ---- operator view --------------------------------------------------------------------- */
"function render(){\n"
" var s=snap,c=el('status'),p=el('statusbody'),a=el('answer');\n"
" p.innerHTML='';a.innerHTML='';\n"
" el('st').textContent=curState||'-';\n"
" el('se').textContent=s?(s.session_active?'active':'idle'):'-';\n"
" el('cy').textContent=s?(s.cycle_index+' (run '+s.cycles_run+')'):'-';\n"
" el('lr').textContent=(s&&s.last_known_result)||'-';\n"
" el('lrr').textContent=(s&&s.last_reason)||'-';\n"
" el('b-start').disabled=!s||curState!=='READY'||!!pending;\n"
" el('b-abort').disabled=!s||!s.session_active||!!pending;\n"
" renderStepper();renderLast();\n"

" if(pending){c.className='card busy';stopTick();\n"
"  put(p,'p','head b','Sending');\n"
"  put(p,'p','sub',verb(pending.intent)+' - waiting for the machine to accept it.');\n"
"  put(put(p,'div','shim'),'i');return;}\n"
" if(flash){c.className='card '+(flash.c==='g'?'good':'err');stopTick();\n"
"  put(p,'p','head '+flash.c,flash.h);put(p,'p','sub',flash.s);return;}\n"

" var w=s&&s.active_wait;\n"
" if(w){c.className='card wait';stopTick();\n"
"  put(p,'p','head w','Waiting for you');\n"
"  put(p,'p','sub',describe(w));\n"
"  if(w.kind==='APPLY_ADJUSTMENT'){var rev=w.display_turns_rev;\n"
"   var b1=put(p,'div','big');put(b1,'span','',(rev>=0?'+':'')+rev);put(b1,'span','u','rev');\n"
"   put(p,'span','dir '+(rev>=0?'t':'l'),rev>=0?'TIGHTEN spoke '+w.target_index\n"
"    :'LOOSEN spoke '+w.target_index);\n"
"  }else if(w.target_index!==undefined&&w.target_index!==null){\n"
"   var rim=(w.kind==='POSITION_TO_RIM_INDEX'||w.kind==='ENTER_RUNOUT');\n"
"   var b2=put(p,'div','big');put(b2,'span','',w.target_index);\n"
"   put(b2,'span','u',rim?'rim index':'spoke');}\n"
"  put(p,'div','enum',w.kind);\n"
"  if(w.expected_intent==='SUBMIT_RUNOUT'){\n"
"   var g=mk('div','fields'),d1=mk('div'),d2=mk('div');\n"
"   put(d1,'label','fl','lateral mm');put(d2,'label','fl','radial mm');\n"
"   var i1=mk('input'),i2=mk('input');\n"
"   i1.id='lat';i1.type='number';i1.step='0.01';i1.inputMode='decimal';i1.placeholder='0.00';\n"
"   i2.id='rad';i2.type='number';i2.step='0.01';i2.inputMode='decimal';i2.placeholder='0.00';\n"
"   d1.appendChild(i1);d2.appendChild(i2);g.appendChild(d1);g.appendChild(d2);a.appendChild(g);\n"
"   var b=mk('button','go wide','Submit runout');\n"
"   b.onclick=function(){submit('SUBMIT_RUNOUT',w.wait_id,\n"
"    {lateral_mm:parseFloat(el('lat').value||'0'),radial_mm:parseFloat(el('rad').value||'0')});};\n"
"   a.appendChild(b);\n"
"  }else{var cb=mk('button','go wide',\n"
"    w.expected_intent==='CONFIRM_ADJUSTMENT_DONE'?'Adjustment applied':'Positioned');\n"
"   cb.onclick=function(){submit(w.expected_intent,w.wait_id);};a.appendChild(cb);}\n"
"  return;}\n"

" var b3=BUSY[curState];\n"
" if(b3&&s&&s.session_active){c.className='card busy';\n"
"  if(!busySince)busySince=Date.now();\n"
"  put(p,'p','head b',b3[0]);put(p,'p','sub',b3[1]);\n"
"  put(put(p,'div','shim'),'i');\n"
"  var e=put(p,'div','el','0.0 s elapsed');e.id='elapsed';\n"
"  put(p,'div','enum',curState);startTick();return;}\n"

" stopTick();\n"
" if(curState==='TERMINAL'||(s&&!s.session_active&&s.last_known_result)){\n"
"  var T=TERM[s&&s.last_known_result]||['Run finished','',''];\n"
"  c.className='card '+(T[2]==='g'?'good':(T[2]==='e'?'err':''));\n"
"  put(p,'p','head '+(T[2]||''),T[0]);put(p,'p','sub',T[1]);\n"
"  if(s&&s.last_reason&&s.last_reason!=='NONE'&&REASON[s.last_reason])\n"
"   put(p,'p','note',REASON[s.last_reason][0]+' - '+REASON[s.last_reason][1]);\n"
"  renderSummaryInto(p);\n"
"  put(p,'div','enum',(s&&s.last_known_result||'')+\n"
"   (s&&s.last_reason&&s.last_reason!=='NONE'?' / '+s.last_reason:''));return;}\n"
" if(curState==='READY'){c.className='card';\n"
"  put(p,'p','head g','Ready');\n"
"  put(p,'p','sub','Press Start truing to begin a session.');return;}\n"
" c.className='card';put(p,'p','head','Standing by');\n"
" put(p,'p','sub','Nothing to confirm right now.');}\n"

/* Only values the firmware actually reported. Nothing here is computed by the page. */
"function renderSummaryInto(p){\n"
" if(!prov)return;\n"
" var v=prov.verification,rows=[];\n"
" if(v){\n"
"  if(v.max_lateral_mm!==undefined)rows.push(['Final lateral runout',v.max_lateral_mm+' mm']);\n"
"  if(v.max_radial_mm!==undefined)rows.push(['Final radial runout',v.max_radial_mm+' mm']);\n"
"  if(v.tension_evaluated!==undefined)rows.push(['Tension verification',\n"
"   v.tension_evaluated?(v.tension_compliant?'passed':'not compliant'):'not verification-grade']);\n"
" }\n"
" if(snap)rows.push(['Cycles run',String(snap.cycles_run)]);\n"
" if(prov.plan&&prov.plan.n_valid_rows!==undefined)\n"
"  rows.push(['Spokes with a usable measurement',prov.plan.n_valid_rows+\n"
"   (nSpokes?(' of '+nSpokes):'')]);\n"
" if(!rows.length)return;\n"
" var g=put(p,'div','meas');g.style.marginTop='12px';\n"
" for(var i=0;i<rows.length;i++){var d=put(g,'div');\n"
"  put(d,'div','lbl',rows[i][0]);put(d,'div','val',rows[i][1]);}}\n"

"function renderStepper(){\n"
" var host=el('stepper');host.innerHTML='';\n"
" var cur=stageOf(curState);\n"
" for(var i=0;i<STAGES.length;i++){\n"
"  var cls=cur<0?'todo':(i<cur?'done':(i===cur?'now':'todo'));\n"
"  if(curState==='TERMINAL')cls=i===0?'done':'todo';\n"
"  var d=put(host,'div',cls);\n"
"  put(d,'span','mk',cls==='done'?'\\u2713':(cls==='now'?'\\u25b6':'\\u00b7'));\n"
"  put(d,'span','',STAGES[i][0]);\n"
"  if(i===1&&lastIdx!==null&&nSpokes)\n"
"   put(d,'span','rt',(cls==='todo'?'':(lastIdx+' / '+nSpokes)));\n"
"  else if(cls==='now')put(d,'span','rt','in progress');}}\n"

"function renderLast(){\n"
" var h=el('last');h.innerHTML='';\n"
" if(!lastMeas){put(h,'p','sub','No spoke has been measured yet in this session.');return;}\n"
" var f=lastMeas;\n"
" put(h,'div','step-of','Spoke '+f.index);\n"
" var g=put(h,'div','meas');\n"
" var d1=put(g,'div');put(d1,'div','lbl','Frequency');\n"
" put(d1,'div','val',f.selected_frequency_hz+' Hz');\n"
" var d2=put(g,'div');put(d2,'div','lbl','Estimated tension');\n"
" put(d2,'div','val',f.tension_n+' N');\n"
" var st=f.status==='valid'?'ok':(f.status==='suspect'?'':'bad');\n"
" var fl=put(h,'span','flag '+st,f.status==='valid'?'VALID':f.status.toUpperCase());\n"
" fl.style.marginTop='11px';fl.style.display='inline-block';\n"
" if(f.reason&&f.reason!=='NONE'&&REASON[f.reason])\n"
"  put(h,'p','note',REASON[f.reason][0]+'. '+REASON[f.reason][1]);\n"
" put(h,'div','enum',f.status+(f.reason&&f.reason!=='NONE'?' / '+f.reason:''));}\n"

/* ---- run details ------------------------------------------------------------------------ */
"function row(host,k,v,x){var d=put(host,'div');put(d,'div','k',k);put(d,'div','v',v);\n"
" if(x)put(d,'div','x',x);}\n"
"function renderRun(){\n"
" var h=el('rundl'),t=el('techdl'),o=el('outcome');\n"
" h.innerHTML='';t.innerHTML='';o.innerHTML='';\n"
" if(!prov){put(h,'p','sub','Press Resync to fetch the run details.');return;}\n"
" var ws2=prov.wheel_state_summary||{};\n"
" row(h,'Wheel',(ws2.n_spokes||'?')+' spokes, '+(ws2.n_rim_angles||'?')+' rim positions',\n"
"  'Machine profile '+prov.machine_profile_id);\n"
" row(h,'Influence model','Artifact '+prov.influence_artifact_id,\n"
"  prov.generating_fingerprint?('Fingerprint recorded and verified at load'):\n"
"  'No fingerprint recorded');\n"
" row(h,'Solver mode',prov.active_layout==='NONE'?'Geometry only':('Layout '+prov.active_layout),\n"
"  (prov.plan&&prov.plan.mean_tension_targeting_applied)?'Mean-tension targeting applied'\n"
"   :'Tension excluded from verification-grade convergence');\n"
" row(h,'Measurements usable for the solve',\n"
"  (ws2.spokes_solver_admissible!==undefined?ws2.spokes_solver_admissible:'?')+' spokes, '+\n"
"  (ws2.runout_solver_admissible!==undefined?ws2.runout_solver_admissible:'?')+' rim readings',\n"
"  (ws2.spokes_verification_grade!==undefined)\n"
"   ?(ws2.spokes_verification_grade+' spokes verification-grade'):'');\n"
" row(h,'Positioning','Manual operator positioning',\n"
"  prov.wheel_position&&prov.wheel_position.operator_confirmed\n"
"   ?'Confirmed by the operator':'Not operator-confirmed');\n"
" row(h,'Runout entry','Manual dial entry','');\n"
" if(prov.contains_non_real_implementations){\n"
"  var wb=put(h,'div','warnbox');\n"
"  put(wb,'b','','Not a physical wheel result. ');\n"
"  wb.appendChild(document.createTextNode(\n"
"   'This session contains synthetic or simulated components, so the numbers demonstrate '+\n"
"   'the workflow, the solver and the DSP path - not the truing of a real wheel.'));}\n"

" if(prov.verification){var v=prov.verification;\n"
"  row(o,'Geometry',v.geometric_converged?'Within tolerance':'Not within tolerance',\n"
"   'lateral '+v.max_lateral_mm+' mm, radial '+v.max_radial_mm+' mm');\n"
"  row(o,'Tension',v.tension_evaluated?(v.tension_compliant?'Within tolerance':\n"
"   'Outside tolerance'):'Not verification-grade',\n"
"   v.reason&&v.reason!=='NONE'&&REASON[v.reason]?REASON[v.reason][1]:'');}\n"
" else{put(o,'p','sub','No verification has been recorded for this cycle yet.');}\n"
" if(prov.plan){row(o,'Plan',prov.plan.valid?'Computed':'Not computed',\n"
"  prov.plan.policy_reason&&prov.plan.policy_reason!=='NONE'?prov.plan.policy_reason:'');}\n"

" row(t,'Session id',String(prov.session_id),'');\n"
" row(t,'Artifact fingerprint',prov.generating_fingerprint||'-','');\n"
" row(t,'Chain profile',String(prov.chain_profile_id),'acoustic DSP constants');\n"
" row(t,'Tension model profile',String(prov.tension_model_profile_id),'');\n"
" row(t,'Machine profile',String(prov.machine_profile_id),'');\n"
" row(t,'Active layout',String(prov.active_layout),'');\n"
" row(t,'Solver version',prov.plan?String(prov.plan.solver_version):'-','');}\n"

"function describe(w){switch(w.kind){\n"
" case 'CONFIRM_SPOKE0_AT_STATION':\n"
"  return 'Rotate the wheel so spoke 0 is at the '+w.station+' station, then confirm.';\n"
" case 'POSITION_TO_SPOKE':\n"
"  return 'Rotate the wheel until spoke '+w.target_index+' is aligned with the '+\n"
"   w.station+' station.';\n"
" case 'POSITION_TO_RIM_INDEX':\n"
"  return 'Rotate the wheel until rim index '+w.target_index+' is at the '+w.station+\n"
"   ' station.';\n"
" case 'POSITION_TO_RIM_ANGLE':\n"
"  return 'Rotate the wheel so rim angle '+w.target_angle_rad+' rad is at the '+w.station+\n"
"   ' station.';\n"
" case 'ENTER_RUNOUT':\n"
"  return 'Read both dial gauges for rim index '+w.target_index+' and enter them below.';\n"
" case 'APPLY_ADJUSTMENT':\n"
"  return 'Turn the nipple on spoke '+w.target_index+' at the '+w.station+' station by '+\n"
"   'the amount shown, then confirm.';\n"
" default: return w.kind+' (index '+w.target_index+', station '+w.station+')';}}\n"

"function showTab(t){tab=t;\n"
" el('v-op').className=t==='op'?'':'hide';\n"
" el('v-run').className=t==='run'?'':'hide';\n"
" el('v-dev').className=t==='dev'?'':'hide';\n"
" el('tab-op').className=t==='op'?'on':'';\n"
" el('tab-run').className=t==='run'?'on':'';\n"
" el('tab-dev').className=t==='dev'?'on':'';\n"
" if(t==='dev')loadIdent();}\n"

"el('tab-op').onclick=function(){showTab('op');};\n"
"el('tab-run').onclick=function(){showTab('run');};\n"
"el('tab-dev').onclick=function(){showTab('dev');};\n"
"el('b-start').onclick=function(){send({cmd:'START_TRUING'});};\n"
"el('b-abort').onclick=function(){send({cmd:'ABORT'});};\n"
"el('b-refresh').onclick=function(){send({cmd:'GET_CURRENT_STATE'});\n"
" send({cmd:'GET_CURRENT_CYCLE_PROVENANCE'});loadIdent();};\n"
"el('b-raw').onclick=function(){rawOpen=!rawOpen;renderRaw();};\n"
"render();renderRun();renderRaw();connect();\n"
"</script></body></html>\n";

#endif /* TRUING_WEB_UI_H */
