/* GENERATED by acoustic_prep/make_golden.py from the research repository's lib/dsp at commit
 * 4f9d35d08a46fde8fb6d165aa7c8b926ec0fd13c. Reference outputs on the recorded excerpts, whose samples are compiled in by
 * fixture_acoustic_pcm.c. Do not edit. */
#include <math.h>
#include <stddef.h>
#include <stdint.h>

#define ACOUSTIC_GOLDEN_N_CASES 3u
#define ACOUSTIC_GOLDEN_MAX_CANDIDATES 8u

extern const int32_t fixture_acoustic_ts00_e2_pcm[];
extern const size_t fixture_acoustic_ts00_e2_pcm_len;
extern const int32_t fixture_acoustic_ts03_e2_pcm[];
extern const size_t fixture_acoustic_ts03_e2_pcm_len;
extern const int32_t fixture_acoustic_d3_e1_pcm[];
extern const size_t fixture_acoustic_d3_e1_pcm_len;
extern const int32_t fixture_acoustic_noise_pcm[];
extern const size_t fixture_acoustic_noise_pcm_len;

typedef struct { float freq_hz, prominence_db, magnitude_db; int bin_index; } acoustic_golden_peak_t;
typedef struct {
    const char *name;
    const int32_t *pcm;
    uint32_t n_samples;
    int onset_sample;
    int window_start_sample;
    int window_n_samples;
    const char *truncated_by;
    int n_fft;
    float f1_hz, f1_magnitude_db, f1_prominence_db;
    int f1_bin_index;
    float f2_hz;              /* NAN when the reference found none */
    float snr_f1_db;
    int n_peaks_in_band;
    int n_strong_peaks;
    int n_candidates;
    acoustic_golden_peak_t candidates[ACOUSTIC_GOLDEN_MAX_CANDIDATES];
    float m0_tension_n, m1_tension_n, m2_tension_n;   /* m2 NAN when the reference rejected it */
    float m2_l_eff_m;
} acoustic_golden_case_t;

static const acoustic_golden_case_t acoustic_golden_cases[3] = {
  {"ts00_e2", fixture_acoustic_ts00_e2_pcm, 38400u, 9600, 11520, 24000, "window_ms", 262144, 423.885838f, 10.850482f, 16.9152285f, 2315, NAN, 45.8997231f, 4, 12, 8, {{432.796696f, 88.9836994f, 30.9112953f, 2364}, {608.215298f, 110.722731f, 31.3820565f, 3322}, {1251.03569f, 21.0247468f, 9.84469588f, 6832}, {1259.92759f, 72.9378427f, 13.629451f, 6881}, {1321.50104f, 34.1782276f, 5.53095122f, 7217}, {1329.73863f, 91.4161368f, 14.6270112f, 7262}, {1837.18128f, 85.2291255f, 8.8037807f, 10033}, {2034.47792f, 79.3219298f, 6.44205805f, 11111}}, 663.650267f, 622.2448f, NAN, NAN},
  {"ts03_e2", fixture_acoustic_ts03_e2_pcm, 38400u, 9600, 11520, 24000, "window_ms", 262144, 379.800237f, 37.9515929f, 110.352584f, 2074, NAN, 75.6111927f, 2, 5, 5, {{379.800237f, 110.352584f, 37.9515929f, 2074}, {444.711641f, 73.6858773f, 29.0598f, 2429}, {1003.36528f, 101.80503f, 28.5744436f, 5480}, {1447.4841f, 80.0791194f, 9.85993917f, 7905}, {1692.80862f, 81.9933219f, 9.87353567f, 9245}}, 532.784917f, 491.379451f, NAN, NAN},
  {"d3_e1", fixture_acoustic_d3_e1_pcm, 38400u, 9600, 11520, 24000, "window_ms", 262144, 432.039438f, 21.3422224f, 90.7855344f, 2360, 864.087024f, 57.3758422f, 3, 7, 7, {{432.039438f, 90.7855344f, 21.3422224f, 2360}, {441.704955f, 23.8592725f, 10.2235416f, 2412}, {588.706558f, 47.526762f, 13.1160029f, 3215}, {608.511222f, 99.6881362f, 26.4407118f, 3323}, {864.087024f, 72.9932517f, 2.17623306f, 4719}, {1250.59269f, 83.1778942f, 11.0275247f, 6830}, {1259.73787f, 39.9326015f, 9.13915118f, 6880}}, 689.426931f, 648.021464f, NAN, NAN},
};
#define ACOUSTIC_GOLDEN_NOISE_PCM fixture_acoustic_noise_pcm
#define ACOUSTIC_GOLDEN_NOISE_N_SAMPLES 12000u
#define ACOUSTIC_GOLDEN_NOISE_RMS_DBFS -70.76515f
